require '../util'

desc 'Creates an application'
task :create do
  db = Aws::DynamoDB::Client.new \
    region: 'ap-northeast-1'
  
  pp table = db.create_table(
    table_name: 'test_table',
    key_schema: [
      {
        attribute_name: 'id',
        key_type: 'HASH'
      }
    ],
    attribute_definitions: [
      {
        attribute_name: 'id',
        attribute_type: 'S'
      }
    ],
    provisioned_throughput: {
      read_capacity_units: 2,
      write_capacity_units: 2
    }
  )
  
  sleep 5
  
  pp result = db.put_item(
    table_name: 'test_table',
    item: {
      id: '1',
    },
  )
  
  sleep 3
  
  pp result = db.get_item(
    table_name: 'test_table',
    key: {
      id: '1'
    }
  )
end
