require '../util'

desc 'Creates a topic'
task :create do
  # Creates a topic
  # @see [[JAWS-UG CLI] SNS:#1 トピックの作成 - Qiita]{@link http://qiita.com/tcsh/items/e05e21e7338668cbf3b8}
  topic = aws <<-SH, binding
    aws sns create-topic
      --name  test-topic
  SH
  
  # Subscribes
  # @see [[JAWS-UG CLI] SNS:#2 通知先の登録 (e-mail) - Qiita]{@link http://qiita.com/tcsh/items/ca81576b0018bfa32cbe}
  print 'endpoint mail address: '
  endpoint = STDIN.gets
  aws <<-SH, binding
    aws sns subscribe
      --protocol               email
      --topic-arn              <%= topic['TopicArn'] %>
      --notification-endpoint  <%= endpoint %>
  SH
  
  # Gets the topic information
  # @see [[JAWS-UG CLI] SNS:#2 通知先の登録 (e-mail) - Qiita]{@link http://qiita.com/tcsh/items/ca81576b0018bfa32cbe}
  aws <<-SH, binding
    aws sns get-topic-attributes
      --topic-arn  <%= topic['TopicArn'] %>
  SH
  
  # Confirms the subscribing
  # @see [[JAWS-UG CLI] SNS:#2 通知先の登録 (e-mail) - Qiita]{@link http://qiita.com/tcsh/items/ca81576b0018bfa32cbe}
  print 'Confirm subscription URL: '
  confirm_url = URI.parse STDIN.gets
  params = Hash[URI.decode_www_form confirm_url.query]
  aws <<-SH, binding
    aws sns confirm-subscription
      --topic-arn                    <%= topic['TopicArn'] %>
      --token                        <%= params['Token'] %>
      --authenticate-on-unsubscribe  true
  SH
  
  # Gets the topic information
  # @see [[JAWS-UG CLI] SNS:#2 通知先の登録 (e-mail) - Qiita]{@link http://qiita.com/tcsh/items/ca81576b0018bfa32cbe}
  aws <<-SH, binding
    aws sns get-topic-attributes
      --topic-arn  <%= topic['TopicArn'] %>
  SH
  
  # Publishes
  # @see [[JAWS-UG CLI] SNS:#3 メッセージの配信 - Qiita]{@link http://qiita.com/tcsh/items/4a37ec0f4b235a85e00c}
  aws <<-SH, binding
    aws sns publish
      --topic-arn  <%= topic['TopicArn'] %>
      --message    'test message'
      --subject    'test subject'
  SH
end
