require '../util'

desc 'Creates a topic'
task :create do
  topic = aws <<-SH, binding
    aws sns create-topic
      --name  test-topic
  SH
  
  print 'endpoint: '
  endpoint = STDIN.gets
  
  aws <<-SH, binding
    aws sns subscribe
       --protocol               'email'
       --topic-arn              <%= topic['TopicArn'] %>
       --notification-endpoint  <%= endpoint %>
  SH
  
  print 'Confirm subscription URL: '
  confirm_url = STDIN.gets
  
  confirm_url = URI.parse confirm_url
  params = Hash[URI.decode_www_form confirm_url.query]
  
  aws <<-SH, binding
    aws sns confirm-subscription
      --topic-arn                     <%= topic['TopicArn'] %>
      --token                         <%= params['Token'] %>
      --authenticate-on-unsubscribe  true
  SH
end
