require '../util'

desc 'Creates a stack'
task :create do
  vpcs = aws <<-SH, binding
    aws ec2 describe-vpcs
      --filters  'Name=tag-key,Values=Name'
                 'Name=tag-value,Values=default'
      --query    'Vpcs[*]'
  SH
  
  # Create a stack
  # @see [AWS CLIで CloudFormationを操作する - aws memo]{@link http://understeer.hatenablog.com/entry/2013/10/18/195500}
  # @see [AWS CLIでサービスの各種コマンドを動かしてみる(CloudFormation編) ｜ Developers.IO]{@link http://dev.classmethod.jp/cloud/aws/awscli-cloudformation/}
  aws <<-SH, binding
    aws cloudformation create-stack
      --region         ap-northeast-1
      --stack-name     test-stack
      --template-body  file://template.json
      --parameters     ParameterKey=VpcId,ParameterValue=<%= vpcs[0]['VpcId'] %>
  SH
end

desc 'Deletes the stack'
task :delete do
  # Delete a stack
  # @see [スタックの削除 - AWS CloudFormation]{@link https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/using-cfn-cli-deleting-stack.html}
  aws <<-SH, binding
    aws cloudformation delete-stack
      --stack-name  test-stack
  SH
end
