require '../util'

desc 'Runs an activities'
task :run do
  commands = [
    'bundle exec ruby activity.rb',
    'bundle exec ruby workflow.rb',
    'bundle exec ruby decider.rb',
  ]
  pids = commands.map do |cmd|
    puts cmd
    pid = fork{exec cmd}
    sleep 1
    pid
  end
  STDIN.gets
  pids.each{|pid| Process.kill 'KILL', pid }
end
