require '../util'

desc 'Runs an activities'
task :run do
  commands = [
    'bundle exec ruby worker.rb',
    'bundle exec ruby decider.rb',
    'bundle exec ruby starter.rb',
  ]
  pids = commands.map do |cmd|
    puts cmd
    pid = fork{exec cmd}
    sleep 1
    pid
  end
  puts 'If you went to stop this process, please enter a return key...'
  STDIN.gets
  pids.each{|pid| Process.kill 'KILL', pid }
end
